const postTypeAction = {
    GET_POSTS_START: "GET_POSTS_START",
    GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
    GET_POSTS_ERROR: "GET_POSTS_ERROR",
    GET_SINGLEPOST_START: "GET_SINGLEPOST_START",
    GET_SINGLEPOST_SUCCESS: "GET_SINGLEPOST_SUCCESS",
    GET_SINGLEPOST_ERROR: "GET_SINGLEPOST_ERROR",
    EDIT_SINGLEPOST_START: "EDIT_SINGLEPOST_START",
    EDIT_SINGLEPOST_SUCCESS: "EDIT_SINGLEPOST_SUCCESS",
    EDIT_SINGLEPOST_ERROR: "EDIT_SINGLEPOST_ERROR",
    DELETE_SINGLEPOST_START: "DELETE_SINGLEPOST_START",
    DELETE_SINGLEPOST_SUCCESS: "DELETE_SINGLEPOST_SUCCESS",
    DELETE_SINGLEPOST_ERROR: "DELETE_SINGLEPOST_ERROR",
}

export default postTypeAction;